theme: jekyll-theme-modernist
title: "COOP Patcher"
description: "Robeth's Unlimited COOP Patch for Borderlands"
github_username: RobethX
show_downloads: false
gems:
  - jekyll-readme-index
readme_index:
  enabled:          true
  remove_originals: false
